Controllers/DetailCatalogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CourseWorkFactoryAutomatization.Models;

namespace CourseWorkFactoryAutomatization.Controllers
{
    public class DetailCatalogController : Controller
    {
        private readonly CourseWorkContext workContext;

        public DetailCatalogController(CourseWorkContext courseWorkContext)
        {
            workContext = courseWorkContext;
        }

        // GET: DetailCatalog
        public IActionResult GetDetailCatalogs()
        {
              return View(workContext.DetailCatalogs.ToList());
        }

        // GET: DetailCatalog/Details/5
        [HttpGet]
        public IActionResult InfoDetailCatalog(int id)
        {

            var detailCatalog =  workContext.DetailCatalogs
                .Include(u => u.Details)
                .ThenInclude(j => j.Technic)
                .FirstOrDefault(m => m.Id == id);

            return View(detailCatalog);
        }

        // GET: DetailCatalog/Create
        [HttpGet]
        public IActionResult CreateDetailCatalog()
        {
            return View();
        }

        // POST: DetailCatalog/Create
        [HttpPost]
        public IActionResult CreateDetailCatalog(DetailCatalog dc)
        {
            workContext.DetailCatalogs.Add(dc);
            workContext.SaveChanges();
            return Redirect("/DetailCatalog/GetDetailCatalogs");
        }

        // POST: DetailCatalog/Edit/5
        public IActionResult EditDetailCatalog(DetailCatalog dc)
        {
            workContext.Entry(dc).State = EntityState.Modified;
            workContext.SaveChanges();
            return Redirect("/DetailCatalog/GetDetailCatalogs");
        }

        [HttpGet]
        public IActionResult EditDetailCatalog(int id)
        {
            return View(workContext.DetailCatalogs.Where(x => x.Id == id).FirstOrDefault());
        }

        // GET: DetailCatalog/Delete/5
        public IActionResult DeleteDetailCatalog(int id, DetailCatalog detailCatalog)
        {
            detailCatalog = workContext.DetailCatalogs.Where(d => d.Id == id).First();
            workContext.DetailCatalogs.Remove(detailCatalog);
            workContext.SaveChanges();
            return Redirect("/DetailCatalog/GetDetailCatalogs");
        }

    }
}

Controllers/DetailController.cs
using CourseWorkFactoryAutomatization.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.EntityFrameworkCore;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace CourseWorkFactoryAutomatization.Controllers
{
    public class DetailController : Controller
    {
        private CourseWorkContext workContext;
        
        
        public IActionResult Index()
        {
            return View();
        }
        public DetailController(CourseWorkContext courseWorkContext)
        {
            workContext = courseWorkContext;
        }
        [HttpGet]
        public IActionResult CreateDetail()
        {
            IEnumerable<Technic> technics = workContext.Technics.ToList();
            ViewBag.Technics = new SelectList(technics, "Id", "Title");
            IEnumerable<DetailCatalog> detailCatalogs = workContext.DetailCatalogs.ToList();
            ViewBag.DetailCatalogs = new SelectList(detailCatalogs, "Id", "DateCreate");
            return View();
        }
        [HttpPost]
        public IActionResult CreateDetail([Bind("Title,Cost,TechnicId,DetailCatalogId")] Detail d)
        {
            bool exists = workContext.Details.Any(u => u.Title == d.Title&& u.Cost == d.Cost);
            Console.WriteLine(exists);
            if (exists == false)
            {
                workContext.Details.Add(d);
                workContext.SaveChanges();
                return Redirect("/Detail/GetDetails");
            }
            else
            {
                IEnumerable<Technic> technics = workContext.Technics.ToList();
                ViewBag.Technics = new SelectList(technics, "Id", "Title");
                IEnumerable<DetailCatalog> detailCatalogs = workContext.DetailCatalogs.ToList();
                ViewBag.DetailCatalogs = new SelectList(detailCatalogs, "Id", "DateCreate");
                return Redirect("/Detail/CreateDetailErr");
            }
            
        }

        public IActionResult GetDetails()
        {
                return View(workContext.Details
                    .Include(j => j.Technic)
                    .Include(u => u.DetailCatalog)
                    .ToList());
        }
        public IActionResult EditDetail(Detail d)
        {

            workContext.Entry(d).State = EntityState.Modified;
            workContext.SaveChanges();
            return Redirect("/Detail/GetDetails");
        }
        [HttpGet]
        public IActionResult EditDetail(int id)
        {
            IEnumerable<Technic> technics = workContext.Technics.ToList();
            ViewBag.Technics = new SelectList(technics, "Id", "Title");
            IEnumerable<DetailCatalog> detailCatalogs = workContext.DetailCatalogs.ToList();
            ViewBag.DetailCatalogs = new SelectList(detailCatalogs, "Id", "DateCreate");
            return View(workContext.Details.Where(x => x.Id == id).FirstOrDefault());
           
        }
        [HttpGet]
        public IActionResult InfoDetails(int id)
        {
            IEnumerable<Technic> technics = workContext.Technics.ToList();
            ViewBag.Technics = new SelectList(technics, "Id", "Title");
            IEnumerable<DetailCatalog> detailCatalogs = workContext.DetailCatalogs.ToList();
            ViewBag.DetailCatalogs = new SelectList(detailCatalogs, "Id", "DateCreate");
            return View(workContext.Details.Where(x => x.Id == id).FirstOrDefault());
        }

        public IActionResult DeleteDetail(int id, Detail detail) 
        {
            detail = workContext.Details.Where(d => d.Id == id).First();
            workContext.Details.Remove(detail);
            workContext.SaveChanges();
            return Redirect("/Detail/GetDetails");
        }


        [HttpGet]
        public IActionResult InfoExpenses()
        {
            ViewBag.Groupps = workContext.Details.GroupBy(p => p.Title)
                  .Select(g => new { Title = g.Key, Countt = g.Count() }).ToList();
            return View();
        }
        [HttpGet]
        public IActionResult CreateDetailErr()
        {
            IEnumerable<Technic> technics = workContext.Technics.ToList();
            ViewBag.Technics = new SelectList(technics, "Id", "Title");
            IEnumerable<DetailCatalog> detailCatalogs = workContext.DetailCatalogs.ToList();
            ViewBag.DetailCatalogs = new SelectList(detailCatalogs, "Id", "DateCreate");
            return View();
        }
    }
}

Controllers/TechnicController.cs
using CourseWorkFactoryAutomatization.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Internal;
using System.Linq;

namespace CourseWorkFactoryAutomatization.Controllers
{
    public class TechnicController : Controller
    {
        private CourseWorkContext workContext;
        public IActionResult Index()
        {
            return View();
        }

        public TechnicController(CourseWorkContext courseWorkContext)
        {
            workContext = courseWorkContext;
        }
        //Create-Get
        [HttpGet]
        public IActionResult CreateTechnic()
        {
            IEnumerable<TechnicManual> technicManuals = workContext.TechnicManuals.ToList();
            ViewBag.TechnicManuals = new SelectList(technicManuals, "Id", "DateCreate");
            return View();
        }
        //Create-Post
        [HttpPost]
        public IActionResult CreateTechnic(Technic t)
        {
            workContext.Technics.Add(t);
            
            workContext.SaveChanges();
            return Redirect("/Technic/GetTechnics");
        }
        //GetTech-Get
        public IActionResult GetTechnics()
        {
            return View(workContext.Technics.Include(u => u.TechnicManual).ToList());
            
        }
        //Info-Get
        [HttpGet]
        public IActionResult InfoTechnics(int id)
        {
            var technic = workContext.Technics.Include(u => u.Details)
            .FirstOrDefault(m => m.Id == id);
            return View(technic);
                //return View(workContext.Technics.Where(det => det.Id == id).FirstOrDefault());
        }
        //Edit-Post
        public IActionResult EditTechnic(Technic t)
        {
            workContext.Entry(t).State = EntityState.Modified;
            workContext.SaveChanges();
            return Redirect("/Technic/GetTechnics");
        }
        //Edit-Get
        [HttpGet]
        public IActionResult EditTechnic(int id)
        {
            IEnumerable<TechnicManual> technicManuals = workContext.TechnicManuals.ToList();
            ViewBag.TechnicManuals = new SelectList(technicManuals, "Id", "DateCreate");
            return View(workContext.Technics.Where(x => x.Id == id).FirstOrDefault());
            
        }

        //Delete-Post
        public IActionResult DeleteTechnic(int id, Technic technic)
        {
            technic = workContext.Technics.Where(d => d.Id == id).First();
            workContext.Technics.Remove(technic);
            workContext.SaveChanges();
            return Redirect("/Technic/GetTechnics");
        }

        [HttpGet]
        public IActionResult TechExpenses()
        {
            ViewBag.Counterr = workContext.Technics
                    .GroupJoin(workContext.Details, tech => tech.Id, det => det.TechnicId,
                    (tech, details) => new
                    {
                        TechId = tech.Title,
                        Countt = details.Count(),
                    });
            return View();
        }
    }
}

Controllers/UserCatalogController.cs
using CourseWorkFactoryAutomatization.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CourseWorkFactoryAutomatization.Controllers
{
    public class UserCatalogController : Controller
    {
        private readonly CourseWorkContext workContext;

        public UserCatalogController(CourseWorkContext courseWorkContext)
        {
            workContext = courseWorkContext;
        }

        // GET: DetailCatalog
        public IActionResult GetUserCatalogs()
        {
            return View(workContext.UserCatalogs.ToList());
        }

        // GET: DetailCatalog/Details/5
        [HttpGet]
        public IActionResult InfoUserCatalog(int id)
        {

            var userCatalog = workContext.UserCatalogs
                .Include(u => u.Users)
                .FirstOrDefault(m => m.Id == id);

            return View(userCatalog);
        }

        // GET: DetailCatalog/Create
        [HttpGet]
        public IActionResult CreateUserCatalog()
        {
            return View();
        }

        // POST: DetailCatalog/Create
        [HttpPost]
        public IActionResult CreateUserCatalog(UserCatalog userCatalog)
        {
            workContext.UserCatalogs.Add(userCatalog);
            workContext.SaveChanges();
            return Redirect("/UserCatalog/GetUserCatalogs");
        }

        // POST: DetailCatalog/Edit/5
        public IActionResult EditUserCatalog(UserCatalog userCatalog)
        {
            workContext.Entry(userCatalog).State = EntityState.Modified;
            workContext.SaveChanges();
            return Redirect("/UserCatalog/GetUserCatalogs");
        }

        [HttpGet]
        public IActionResult EditUserCatalog(int id)
        {
            return View(workContext.UserCatalogs.Where(x => x.Id == id).FirstOrDefault());
        }

        // GET: DetailCatalog/Delete/5
        public IActionResult DeleteUserCatalog(int id, UserCatalog userCatalog)
        {
            userCatalog = workContext.UserCatalogs.Where(d => d.Id == id).First();
            workContext.UserCatalogs.Remove(userCatalog);
            workContext.SaveChanges();
            return Redirect("/UserCatalog/GetUserCatalogs");
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CourseWorkFactoryAutomatization</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CourseWorkFactoryAutomatization.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CourseWorkFactoryAutomatization</a>
            </div>
            <div class="collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>
                        <a class="nav-link pos-r" asp-area="" asp-controller="Account" asp-action="Login"> Войти </a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CourseWorkFactoryAutomatization
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout_Accountant.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CourseWorkFactoryAutomatization</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CourseWorkFactoryAutomatization.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index_Accountant">CourseWorkFactoryAutomatization</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Detail" asp-action="GetDetails">Общий список деталей</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DetailCatalog" asp-action="GetDetailCatalogs">Каталоги деталей</a>
                        </li>
                    </ul>
                </div>
                <div class="collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark pos-r" asp-area="" asp-controller="Account" asp-action="Logout"> Выйти </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CourseWorkFactoryAutomatization
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout_Admin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CourseWorkFactoryAutomatization</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CourseWorkFactoryAutomatization.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index_Admin">CourseWorkFactoryAutomatization</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="GetUsers">Общий список пользователей</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserCatalog" asp-action="GetUserCatalogs">Каталоги пользователей</a>
                        </li>
                    </ul>
                </div>
                <div class="collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item item-3">
                            <a class="nav-link text-dark pos-r" asp-controller="Account" asp-action="Logout" class="header-top-3">Выйти</a>
                        </li>
                        <li class="nav-item item-3">
                            <a class="nav-link text-dark pos-r" asp-controller="Account" asp-action="CreateUser" class="header-top-3">Регистрация пользователей</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CourseWorkFactoryAutomatization
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout_SuperVisor.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CourseWorkFactoryAutomatization</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CourseWorkFactoryAutomatization.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index_SuperVisor">CourseWorkFactoryAutomatization</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Technic" asp-action="GetTechnics">Общий список техники</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TechnicManual" asp-action="GetTechnicManuals"> Каталоги техники</a>
                        </li>
                    </ul>
                </div>
                <div class="collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark pos-r" asp-area="" asp-controller="Account" asp-action="Logout"> Выйти </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CourseWorkFactoryAutomatization
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>